# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authFirstName', models.CharField(max_length=45)),
                ('authLastName', models.CharField(max_length=45)),
                ('authNotes', models.CharField(max_length=255)),
                ('authCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('authUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksTitle', models.CharField(max_length=45)),
                ('booksCreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='authors',
            name='authBooksManyCon',
            field=models.ManyToManyField(related_name='publisher', to='booksAuthorsApp.Books'),
        ),
    ]
