# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-19 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='booksDescription',
            field=models.CharField(default='this is a default description', max_length=255),
            preserve_default=False,
        ),
    ]
